version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      VERSION: '2.9.1'
      MAINTAINER: '@raza231198'
      VENDOR: 'asus'
      CODENAME: 'X00P'
      FLAVOR: 'eng'
      PB_OFFICIAL: 'true'
      EXTRA_CMD: "rm -rf vendor/pb && git clone -b pb https://github.com/PitchBlackRecoveryProject-Devices/vendor_pb vendor/pb"
      CHANGELOG: |
        - Delete it plox
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject-Devices/vendor_pb/pb/build.sh
            source build.sh
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-9.0'
          context: org-global
